export const productItemPageLocators = {
    productItem: ".product-item, .product-detail",
    productItemTitle: "h1.product__title.heading",
    productItemPrice: "[data-product-card-price-from-cart]",
    productImage: ".product__one-photo",
    productDescription: ".product-description, .item-description",
    productSpecifications: ".product-specs, .specifications",
    addToCartButton: ".add-to-cart, .add-cart-counter__btn",
    quantitySelector: ".quantity-selector, .qty-selector",
    quantityInput: "[data-add-cart-counter-count]",
    quantityIncrease: "[data-add-cart-counter-plus]",
    quantityDecrease: "[data-add-cart-counter-minus]",
    productVariants: ".product-variants, .variants",
    productReviews: ".product-reviews, .reviews",
    relatedProducts: ".related-products, .similar-items",
    breadcrumb: ".breadcrumb, .breadcrumbs",
    backButton: ".back-button, .back-link",
    productTitle: "h1, .product-title, .item-title",
    favoriteButton: ".btn-icon.icon-favorites",
    successMessage: ".micro-alert",
    favoriteSuccessMessage: '.micro-alert-item.is-success-notice'
}
