export const productItemPageLocators = {
    productItem: ".product-item, .product-detail",
    productItemTitle: ".product-title, .product-name",
    productItemPrice: ".product-price, .item-price",
    productImage: ".product-image, .item-image",
    productDescription: ".product-description, .item-description",
    productSpecifications: ".product-specs, .specifications",
    addToCartButton: ".add-to-cart, .add-cart-counter__btn",
    quantitySelector: ".quantity-selector, .qty-selector",
    quantityInput: ".quantity-input, .qty-input",
    quantityIncrease: ".quantity-increase, .qty-plus",
    quantityDecrease: ".quantity-decrease, .qty-minus",
    productVariants: ".product-variants, .variants",
    productReviews: ".product-reviews, .reviews",
    relatedProducts: ".related-products, .similar-items",
    breadcrumb: ".breadcrumb, .breadcrumbs",
    backButton: ".back-button, .back-link",
    productTitle: "h1, .product-title, .item-title",
    favoriteButton: ".favorite-btn, .wishlist-btn, .like-btn",
    successMessage: ".success-message, .alert-success, .notification-success, .toast-success",
    favoriteSuccessMessage: ".favorite-success, .wishlist-success, .like-success, .alert-favorite"
}
