export const HomePageLocators = {
    modalCloseButton: '.modal__btn-close',
    searchField: 'input[name="q"]',
    searchFieldButton: '.header__search-btn',
    itemInHomePage: '.product-preview__content',
    itemAddButton: '.button.add-cart-counter__btn',
    basketHome: '.cart-fixed-btn',
    itemTitle: '.product-preview__title',
    itemPrice: '.product-preview__price-cur',
    headerSearchField: 'header input[name="q"], .header__search-field',
    mainSearchField: 'input[name="q"], .search-form input',
    productGrid: '.product-grid, .products-grid',
    productCard: '.product-preview, .catalog-item',
    productTitle: '.product-preview__title, .catalog-item__title',
    productPrice: '.product-preview__price, .catalog-item__price',
    addToCartButton: '.add-cart-counter__btn, .buy-button',
    cartIcon: '.cart-fixed-btn, .shopping-cart',
    logo: '.header__logo, .site-logo',
    basketCount: '.cart-count, .basket-count, .cart-counter, [data-cart-count]',
    basketQuantity: '[data-cart-positions-count]',
}